#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
6B_semantic_map_comparision.py

Per-frame semantic IoU + aggregated summary.

Compares:
    SegFormer real-world semantic maps
    vs
    CARLA replay semantic maps generated by Step 5A / 5A_sd.

Reads from (project root):
    data/processed_dataset/<BAG>/semantic_maps/*.png
    data/replay_dataset/<BAG>/only_carla/semantic/*.png

Writes to (project root):
    results/semantic/<BAG>/
        <frame>_iou.json
        <frame>_vis.png
        summary.json

Notes:
    - This script bypasses 6A_copy_data_for_validation.py.
    - Semantic replay maps are static per bag, not per driving run.
    - Both GT and prediction are forced to 512x512 using NEAREST resize.
"""

import argparse
import json
import shutil
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import ListedColormap
from PIL import Image


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent

DEFAULT_BAG_NAME = "reference_bag.bag"

TARGET_SIZE = (512, 512)  # (W, H)
NUM_CLASSES = 3
COLOR_TOLERANCE = 15

COLOR_TO_CLASS = {
    (0, 0, 0): 0,          # background
    (0, 0, 142): 1,        # car
    (128, 64, 128): 2,     # road
}

SUMMARY_KEYS = [
    ("background", "iou_background"),
    ("car", "iou_car"),
    ("road", "iou_road"),
    ("mIoU", "mean_iou"),
]


def parse_args():
    parser = argparse.ArgumentParser(
        description="Semantic IoU: SegFormer real-world vs CARLA replay."
    )
    parser.add_argument(
        "--bag-name",
        default=DEFAULT_BAG_NAME,
        help=(
            "Bag filename including .bag extension, or bag stem. "
            f"Default: {DEFAULT_BAG_NAME}"
        ),
    )
    parser.add_argument(
        "--summary-only",
        action="store_true",
        help="Only aggregate existing *_iou.json files into summary.json.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Reprocess frames even if *_iou.json already exists.",
    )
    parser.add_argument(
        "--clear-results",
        action="store_true",
        help="Delete the result folder before processing.",
    )
    return parser.parse_args()


def get_paths(bag_name):
    bag_stem = Path(bag_name).stem

    gt_dir = (
        PROJECT_ROOT
        / "data"
        / "processed_dataset"
        / bag_stem
        / "semantic_maps"
    )
    pred_dir = (
        PROJECT_ROOT
        / "data"
        / "replay_dataset"
        / bag_stem
        / "only_carla"
        / "semantic"
    )
    results_dir = PROJECT_ROOT / "results" / bag_stem / "semantic"

    return bag_stem, gt_dir, pred_dir, results_dir


def load_image(path):
    try:
        img = Image.open(path).convert("RGB")
        if img.size != TARGET_SIZE:
            img = img.resize(TARGET_SIZE, resample=Image.Resampling.NEAREST)
        return np.array(img)
    except Exception as exc:
        print(f"[WARN] Could not open {path}: {exc}")
        return None


def rgb_to_class_map(img_arr):
    class_map = np.zeros(img_arr.shape[:2], dtype=np.int32)
    img_int = img_arr.astype(int)

    for color, class_id in COLOR_TO_CLASS.items():
        color_arr = np.array(color, dtype=int)
        diff = np.abs(img_int - color_arr)
        mask = np.all(diff <= COLOR_TOLERANCE, axis=-1)
        class_map[mask] = class_id

    return class_map


def compute_confusion(gt_cls, pred_cls):
    mask = (gt_cls >= 0) & (gt_cls < NUM_CLASSES)
    gt = gt_cls[mask]
    pred = pred_cls[mask]

    return np.bincount(
        NUM_CLASSES * gt.astype(int) + pred.astype(int),
        minlength=NUM_CLASSES ** 2,
    ).reshape(NUM_CLASSES, NUM_CLASSES)


def compute_iou(confusion):
    intersection = np.diag(confusion)
    gt_sum = confusion.sum(axis=1)
    pred_sum = confusion.sum(axis=0)
    union = gt_sum + pred_sum - intersection

    return intersection / np.maximum(union, 1)


def extract_frame_id(path):
    stem = path.stem
    stem = stem.replace("seg_", "").replace("frame_", "")

    try:
        return int(stem)
    except ValueError:
        return None


def find_pred_file(pred_dir, frame_id):
    candidates = [
        pred_dir / f"{frame_id:06d}.png",
        pred_dir / f"frame_{frame_id:06d}.png",
    ]

    for candidate in candidates:
        if candidate.exists():
            return candidate

    return None


def match_files(gt_dir, pred_dir):
    gt_files = sorted([
        p for p in gt_dir.iterdir()
        if p.is_file() and p.suffix.lower() == ".png"
    ])

    matched = []
    missing = []
    skipped = []

    for gt_path in gt_files:
        frame_id = extract_frame_id(gt_path)

        if frame_id is None:
            skipped.append(gt_path.name)
            continue

        pred_path = find_pred_file(pred_dir, frame_id)

        if pred_path is None:
            missing.append(gt_path.name)
        else:
            matched.append((gt_path, pred_path))

    return gt_files, matched, missing, skipped


def save_diff_figure(gt_cls, pred_cls, out_path):
    diff = gt_cls != pred_cls
    cmap = ListedColormap(["black", "green", "red"])

    fig, axes = plt.subplots(1, 3, figsize=(12, 4))

    panels = [
        (gt_cls, "GT (Real / SegFormer)", cmap),
        (diff, "Diff (White = Mismatch)", "gray"),
        (pred_cls, "Pred (Sim / CARLA)", cmap),
    ]

    for ax, (image, title, panel_cmap) in zip(axes, panels):
        ax.imshow(
            image,
            cmap=panel_cmap,
            vmin=0 if panel_cmap != "gray" else None,
            vmax=NUM_CLASSES - 1 if panel_cmap != "gray" else None,
            interpolation="nearest",
        )
        ax.set_title(title)
        ax.axis("off")

    plt.tight_layout()
    fig.savefig(out_path, dpi=120)
    plt.close(fig)


def process_frame(gt_path, pred_path, results_dir):
    gt_arr = load_image(gt_path)
    pred_arr = load_image(pred_path)

    if gt_arr is None or pred_arr is None:
        return None

    gt_cls = rgb_to_class_map(gt_arr)
    pred_cls = rgb_to_class_map(pred_arr)

    confusion = compute_confusion(gt_cls, pred_cls)
    iou = compute_iou(confusion)

    valid = confusion.sum(axis=1) > 0
    mean_iou = float(iou[valid].mean()) if valid.any() else None

    result = {
        "gt_file": gt_path.name,
        "pred_file": pred_path.name,
        "target_size": {
            "width": TARGET_SIZE[0],
            "height": TARGET_SIZE[1],
        },
        "color_tolerance": COLOR_TOLERANCE,
        "iou_background": float(iou[0]),
        "iou_car": float(iou[1]),
        "iou_road": float(iou[2]),
        "mean_iou": mean_iou,
        "confusion_matrix": confusion.tolist(),
    }

    out_json = results_dir / f"{gt_path.stem}_iou.json"
    out_vis = results_dir / f"{gt_path.stem}_vis.png"

    with open(out_json, "w") as f:
        json.dump(result, f, indent=2)

    save_diff_figure(gt_cls, pred_cls, out_vis)

    return result


def aggregate_results(results_dir):
    json_files = sorted(results_dir.glob("*_iou.json"))

    if not json_files:
        return None

    values = {key: [] for _, key in SUMMARY_KEYS}

    for json_file in json_files:
        with open(json_file, "r") as f:
            data = json.load(f)

        for _, key in SUMMARY_KEYS:
            if data.get(key) is not None:
                values[key].append(data[key])

    def stats(items):
        return {
            "mean": float(np.mean(items)) if items else None,
            "std": float(np.std(items)) if items else None,
            "n": len(items),
        }

    summary = {
        "frames": len(json_files),
        "target_size": {
            "width": TARGET_SIZE[0],
            "height": TARGET_SIZE[1],
        },
        "color_tolerance": COLOR_TOLERANCE,
        "classes": {
            label: stats(values[key])
            for label, key in SUMMARY_KEYS
        },
    }

    return summary


def print_and_save_summary(results_dir):
    summary = aggregate_results(results_dir)

    if summary is None:
        print(f"[INFO] No *_iou.json files found in {results_dir}")
        return

    print("\n" + "=" * 80)
    print(f"Aggregated over {summary['frames']} frames")
    print(f"  {'class':<14} {'mean':>8} {'std':>8} {'n':>6}")
    print(f"  {'-' * 14} {'-' * 8} {'-' * 8} {'-' * 6}")

    for label, _ in SUMMARY_KEYS:
        s = summary["classes"][label]
        mean = f"{s['mean']:.4f}" if s["mean"] is not None else "n/a"
        std = f"{s['std']:.4f}" if s["std"] is not None else "n/a"
        print(f"  {label:<14} {mean:>8} {std:>8} {s['n']:>6}")

    print("=" * 80)

    out_path = results_dir / "summary.json"
    with open(out_path, "w") as f:
        json.dump(summary, f, indent=2)

    print(f"[INFO] Saved: {out_path}")


def validate_input_dirs(gt_dir, pred_dir):
    if not gt_dir.exists():
        print(f"[ERROR] GT directory does not exist: {gt_dir}")
        print("[HINT] Expected: data/processed_dataset/<BAG>/semantic_maps")
        sys.exit(1)

    if not pred_dir.exists():
        print(f"[ERROR] Prediction directory does not exist: {pred_dir}")
        print("[HINT] Expected: data/replay_dataset/<BAG>/only_carla/semantic")
        sys.exit(1)


def main():
    args = parse_args()
    bag_stem, gt_dir, pred_dir, results_dir = get_paths(args.bag_name)

    print("=" * 80)
    print("SEMANTIC IoU: SegFormer real-world vs CARLA replay")
    print("=" * 80)
    print(f"[INFO] Project root: {PROJECT_ROOT}")
    print(f"[INFO] Bag stem:     {bag_stem}")
    print(f"[INFO] GT dir:       {gt_dir}")
    print(f"[INFO] Pred dir:     {pred_dir}")
    print(f"[INFO] Results dir:  {results_dir}")
    print(f"[INFO] Target size:  {TARGET_SIZE}")
    print(f"[INFO] Tolerance:    {COLOR_TOLERANCE}")
    print("=" * 80)

    if args.summary_only:
        if not results_dir.exists():
            print(f"[ERROR] Results directory does not exist: {results_dir}")
            sys.exit(1)
        print_and_save_summary(results_dir)
        return

    validate_input_dirs(gt_dir, pred_dir)

    if args.clear_results and results_dir.exists():
        print(f"[INFO] Clearing results directory: {results_dir}")
        shutil.rmtree(results_dir)

    results_dir.mkdir(parents=True, exist_ok=True)

    gt_files, matched, missing, skipped = match_files(gt_dir, pred_dir)

    if not gt_files:
        print(f"[ERROR] No PNG files found in GT directory: {gt_dir}")
        sys.exit(1)

    print(f"[INFO] Found GT files: {len(gt_files)}")
    print(f"[INFO] Matched pairs:  {len(matched)}")

    if skipped:
        print(f"[WARN] Skipped GT files without numeric frame ID: {len(skipped)}")
        for name in skipped[:5]:
            print(f"       {name}")

    if missing:
        print(f"[WARN] Missing predictions: {len(missing)}")
        for name in missing[:5]:
            print(f"       {name}")

    if not matched:
        print("[ERROR] No matching GT/PRED pairs. Aborting.")
        sys.exit(1)

    if args.force:
        to_process = matched
    else:
        to_process = [
            (gt_path, pred_path)
            for gt_path, pred_path in matched
            if not (results_dir / f"{gt_path.stem}_iou.json").exists()
        ]

    print(f"[INFO] Already processed: {len(matched) - len(to_process)}")
    print(f"[INFO] To process:        {len(to_process)}")

    for gt_path, pred_path in to_process:
        result = process_frame(gt_path, pred_path, results_dir)

        if result is None:
            continue

        miou = result["mean_iou"]
        miou_text = f"{miou:.4f}" if miou is not None else "n/a"
        print(f"[OK] {gt_path.name} -> {pred_path.name} | mIoU: {miou_text}")

    print_and_save_summary(results_dir)


if __name__ == "__main__":
    main()